### ISSUE TITLE
Boot2docker asking for login after piho init

### ISSUE THREAD

**Issue by vallettea** [xdissent/pihotenuse#1]
Hello,

thanks for this amazing project.
I'm trying to use your lib but I have a problem once I run `piho init`:

```
vallette@Mac-3 ~/Desktop/pihotenuse (master)$ piho init                                                         
Initializing boot2docker
Starting boot2docker
docker@localhost's password:
```

[boot2docker shouldn't ask for a password](https://github.com/boot2docker/boot2docker/issues/405)

I also tried `piho boot2docker ssh` which asks for a password whereas `boot2docker ssh` works perfectly.
Any idea ? what version of boot2docker are you using ?

**Comment by vallettea** [comment]
I have Boot2Docker-cli version: v1.4.1

**Comment by xdissent** [comment]
LOL, literally moments before you posted this, I blew away my boot2docker install and upgraded to 1.6.0. I kept my piho stuff around, assuming the existing VM and boot2docker profile would still work, so `file ~/.pihotenuse/boot2docker.iso` tells my I was running boot2docker 1.5.0. Unfortunately, even with my existing VM and profile (and ISO), it started giving me the password prompt. I eventually blew away my piho stuff with no effect. But now I realize it wasn't really the upgrade at all...

The password problem is easy - it's a NAT port collision between the default boot2docker VM and the piho boot2docker VM. I've got a patch for that coming right up (it just adds `SSHPort = 2023` to the boot2docker profile). You could probably patch up an existing piho VM by manually editing settings and your profile, but like I said, I blew mine away already. =) Of course, just deleting the default boot2docker VM works too if you don't need it.

Another problem I've just noticed is that the `dockerfiles` docker hub account is gone. I remember reading about them shutting it down because more people wanted to provide "official" hub repos, but I didn't realize they yanked em entirely. I already have a patch that switches piho.sh to the official repo too.

I'm just double checking to make sure no other issues pop up and then I'll push an update.

**Comment by vallettea** [comment]
:+1: thanks

**Comment by xdissent** [comment]
Thanks for the feedback!

**Comment by vallettea** [comment]
Sorry about that, but after i pulled your modifications, i still have the same problem.

**Comment by xdissent** [comment]
Aw, I was pretty pleased that `piho upgrade` worked as expected for me after I released the new version! Then again, I had manually removed my pihotenuse-VM in Virtualbox and deleted everything in `~/.pihotenuse`. If you're trying to keep an old install around, you may have to manually add `SSHPort = 2203` to `~/.pihotenuse/b2d.profile`. Then you should be able to run `piho b2d down` to temporarily stop your VM. Then open the pihotenuse-VM settings in Virtual Box, go to Network -> Adapter 1 -> Port Forwarding and make sure the "Host Port" for "ssh" is 2203. THEN `piho upgrade` should restart your pihotenuse-VM on the correct port and update the `piho` bin within the docker container and qemu env. Sorry about that - wasn't really planning for this kind of change in the regular upgrade path!

**Comment by vallettea** [comment]
works fine !! thx

**Comment by xdissent** [comment]
Killerrrr! Please let me know if shit goes south
